<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Place;
use App\Models\User;

class PlaceSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first(); // Pastikan ada user

        $places = [
            // CAFE
            [
                'name' => 'Titik Atas',
                'category' => 'cafe',
                'description' => 'Cafe dengan suasana hangat di kawasan Setia Budi, cocok untuk menikmati senja Semarang dengan kopi dan obrolan santai.',
                'address' => 'Jl. Setia Budi No.5, Tinjomoyo, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50262',
                'district' => 'Banyumanik',
                'phone' => '085726829829',
                'instagram' => '@titikatassemarang',
                'opening_hours' => '17:00 - 23:30',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Butterhalf',
                'category' => 'cafe',
                'description' => 'Tempat ngopi modern dengan interior minimalis, terkenal dengan pastry manis dan ambience cozy di pusat kota.',
                'address' => 'Jl. Imam Bonjol No.188A, Pendrikan Kidul, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50139',
                'district' => 'Semarang Tengah',
                'phone' => '08112909975',
                'instagram' => '@butterhalf.co',
                'opening_hours' => '08:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Nyctophily Coffee',
                'category' => 'cafe',
                'description' => 'Cafe bernuansa artsy, ideal untuk pecinta kopi yang ingin bekerja atau bersantai di area Banyumanik.',
                'address' => 'Jl. Tembalang Sel. IV No.2, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268',
                'district' => 'Banyumanik',
                'phone' => '081575441803',
                'instagram' => '@nyctophilycoffee',
                'opening_hours' => '09:00 - 22:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Burjo Kane',
                'category' => 'cafe',
                'description' => 'Burjo kekinian dengan menu lengkap, buka hingga tengah malam, jadi pilihan anak muda untuk nongkrong murah meriah.',
                'address' => 'Jl. Jatimulyo No.8, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268',
                'district' => 'Banyumanik',
                'phone' => '085280011100',
                'instagram' => '@burjokane.smg',
                'opening_hours' => '09:00 - 00:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Loeka Kopi',
                'category' => 'cafe',
                'description' => 'Cafe dengan jam buka panjang, menawarkan suasana hangat dan menu kopi yang variatif untuk menemani malam.',
                'address' => 'Jl. Tembalang Selatan V No.41, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268',
                'district' => 'Banyumanik',
                'phone' => '085225777834',
                'instagram' => null,
                'opening_hours' => '07:00 - 02:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Ruang Interaksi',
                'category' => 'cafe',
                'description' => 'Cafe dengan konsep komunitas, sering jadi tempat diskusi, acara kreatif, dan nongkrong santai di Semarang Barat',
                'address' => 'Jl. Jenderal Sudirman No.108, Cabean, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141',
                'district' => 'Semarang Barat',
                'phone' => '082226600367',
                'instagram' => 'ruanginteraksi.smg',
                'opening_hours' => '09:00 - 00:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Ideologist',
                'category' => 'cafe',
                'description' => 'Spot instagramable dengan desain modern, cocok untuk nongkrong 24 jam bersama teman atau kerja remote',
                'address' => 'Gombel Jl. Setia Budi No.28, Ngesrep, Banyumanik, Semarang City, Central Java 50262',
                'district' => 'Banyumanik',
                'phone' => '085640653786',
                'instagram' => '@ideologist.space',
                'opening_hours' => 'Buka 24 Jam',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Pushup Coffee',
                'category' => 'cafe',
                'description' => 'Cafe dengan jam buka fleksibel, suasana cozy, dan menu kopi yang pas untuk menemani obrolan panjang.',
                'address' => 'Jl. Gombel Lama, Tinjomoyo, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50254',
                'district' => 'Banyumanik',
                'phone' => null,
                'instagram' => '@pushupcoffeeofficial',
                'opening_hours' => '07:00-23:00 (senin-kamis), 07:00-00:00 (jumat-sabtu)',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Dirasa Kopi',
                'category' => 'cafe',
                'description' => 'Cafe 24 jam dengan vibe homey, jadi pilihan favorit mahasiswa dan pekerja malam di Semarang Selatan.',
                'address' => 'Jl. Veteran No.60, Mugassari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50231',
                'district' => 'Semarang Selatan',
                'phone' => '081227282527',
                'instagram' => '@at.dirasakopi',
                'opening_hours' => 'Buka 24 Jam',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Jabat Kopi',
                'category' => 'cafe',
                'description' => 'Cafe malam dengan nuansa hangat, cocok untuk kumpul santai sambil menikmati kopi di Mugassari.',
                'address' => 'Jl. Mugas Dalam X No.38, Mugassari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50249',
                'district' => 'Semarang Selatan',
                'phone' => null,
                'instagram' => '@jabatkopi.smg',
                'opening_hours' => '16:00-00:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],

            // RESTAURANT
            [
                'name' => 'Pocha 1988',
                'category' => 'restaurant',
                'description' => 'Restoran ala Korea dengan suasana vibrant, cocok untuk makan bersama teman dengan menu khas street food Korea.',
                'address' => 'Jl. MH Thamrin No.52, Miroto, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50133',
                'district' => 'Semarang Tengah',
                'phone' => null,
                'instagram' => '@1988pocha_smrg',
                'opening_hours' => '15:00-23:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Kyo F&B',
                'category' => 'restaurant',
                'description' => 'Restoran modern dengan menu fusion, menawarkan pengalaman kuliner unik di Semarang Barat.',
                'address' => 'Jl. Puspanjolo Timur raya V No.15, Cabean, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141',
                'district' => 'Semarang Barat',
                'phone' => '08112726639',
                'instagram' => '@kyo_fnb',
                'opening_hours' => '07:00 - 21:30',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Nudel Bar',
                'category' => 'restaurant',
                'description' => 'Restoran dengan spesialisasi mie, suasana casual dan cocok untuk makan cepat maupun santai',
                'address' => 'Jl. Setia Budi No.25, Tinjomoyo, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50262',
                'district' => 'Banyumanik',
                'phone' => '08112877777',
                'instagram' => '@nudelbar.id',
                'opening_hours' => '07:00 - 22:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Daeng Baba Resto',
                'category' => 'restaurant',
                'description' => 'Restoran dengan cita rasa Nusantara, menghadirkan menu tradisional dengan sentuhan modern.',
                'address' => 'Jl. Veteran No.41, Lempongsari, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50231',
                'district' => 'Semarang Tengah',
                'phone' => '02486449143',
                'instagram' => '@daeng_baba_resto',
                'opening_hours' => '09:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Pesta Keboen',
                'category' => 'restaurant',
                'description' => 'Restoran keluarga dengan nuansa vintage, terkenal sebagai tempat makan nostalgia di Semarang.',
                'address' => 'Jl. Veteran No.29, Lempongsari, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50231',
                'district' => 'Semarang Tengah',
                'phone' => '0248310620',
                'instagram' => '@pestakeboen',
                'opening_hours' => '10:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Oti Heritage Veteran',
                'category' => 'restaurant',
                'description' => 'Restoran ayam goreng legendaris dengan resep turun-temurun, jadi favorit warga Semarang',
                'address' => 'Jl. Veteran No.7, Lempongsari, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50231',
                'district' => 'Semarang Tengah',
                'phone' => '081129408989',
                'instagram' => '@otichicken.id',
                'opening_hours' => '10:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Tyler\'s',
                'category' => 'restaurant',
                'description' => 'Restoran dengan konsep modern, menyajikan menu western dan lokal dengan suasana cozy.',
                'address' => 'Jl. Tri Lomba Juang No.5, Mugassari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50249',
                'district' => 'Semarang Selatan',
                'phone' => '02476530420',
                'instagram' => null,
                'opening_hours' => '11:00 - 23:30',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],

            // STREET FOOD
            [
                'name' => 'Sarang Seafood Rafa',
                'category' => 'street-food',
                'description' => 'Street food populer dengan menu seafood segar, jadi pilihan malam hari di Semarang Barat.',
                'address' => 'Jl. Jenderal Sudirman No.122, Cabean, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141',
                'district' => 'Semarang Barat',
                'phone' => '087832087647',
                'instagram' => null,
                'opening_hours' => '18:00 - 23:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Pleburan Street Undip',
                'category' => 'street-food',
                'description' => 'Pusat jajanan malam mahasiswa, ramai dengan berbagai pilihan makanan murah meriah.',
                'address' => '2C4F+G2H, Jl. Imam Bardjo SH, Pleburan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah',
                'district' => 'Semarang Selatan',
                'phone' => null,
                'instagram' => null,
                'opening_hours' => '18:00 - 00:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Banjir Kanal',
                'category' => 'street-food',
                'description' => 'Street food area dengan suasana ramai, cocok untuk kuliner malam bersama teman.',
                'address' => '2C82+XJM, Jl. Bojong Salaman, Cabean, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141',
                'district' => 'Semarang Barat',
                'phone' => null,
                'instagram' => null,
                'opening_hours' => '18:00 - 00:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Kopi Kongkow 313',
                'category' => 'street-food',
                'description' => 'Warung kopi sederhana dengan suasana santai, jadi tempat nongkrong warga Mugassari.',
                'address' => 'Jl. Mugas Bar. IV, Mugassari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah',
                'district' => 'Semarang Selatan',
                'phone' => null,
                'instagram' => null,
                'opening_hours' => '15:00-23:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],

            // BAKERY
            [
                'name' => 'Levure Bakehouse',
                'category' => 'bakery',
                'description' => 'Bakery modern dengan roti artisan, cocok untuk pecinta pastry premium.',
                'address' => 'Jl. Pandanaran 2 No.2A, Mugassari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50249',
                'district' => 'Semarang Selatan',
                'phone' => '081234788709',
                'instagram' => '@levure.bakehouse',
                'opening_hours' => '07:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Dyriana Bakery & Cafe',
                'category' => 'bakery',
                'description' => 'Bakery legendaris Semarang, terkenal dengan kue dan roti yang jadi oleh-oleh khas.',
                'address' => 'Jl. Pandanaran No.51A, Randusari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50244',
                'district' => 'Semarang Selatan',
                'phone' => '08156512000',
                'instagram' => '@dyriana.bakery',
                'opening_hours' => '06:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Han\'s Bakery',
                'category' => 'bakery',
                'description' => 'Bakery lokal dengan pilihan roti fresh setiap hari, suasana hangat untuk keluarga.',
                'address' => 'Jl. Sukun Raya No.41, Srondol Wetan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50263',
                'district' => 'Banyumanik',
                'phone' => '087700393402',
                'instagram' => '@hans_bakery',
                'opening_hours' => '07:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Fancy Bakery Tembalang',
                'category' => 'bakery',
                'description' => 'Bakery dengan variasi kue manis, cocok untuk mahasiswa dan warga sekitar Tembalang.',
                'address' => 'No.38 F, Jl. Ngesrep Tim. V, Sumurboto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50269',
                'district' => 'Tembalang',
                'phone' => '08156690360',
                'instagram' => '@fancy_bakery',
                'opening_hours' => '07:30 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Fiven Cake Tembalang',
                'category' => 'bakery',
                'description' => 'Toko kue dengan spesialisasi cake custom, jadi pilihan untuk acara spesial.',
                'address' => 'Jl. Jatimulyo No.1, RT.4/RW.3, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275',
                'district' => 'Tembalang',
                'phone' => null,
                'instagram' => null,
                'opening_hours' => '10:00 - 22:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],

            // DRINK AREA
            [
                'name' => 'Djagongan Liquor & Eatery',
                'category' => 'drink-area',
                'description' => 'Bar dengan suasana hangat, cocok untuk menikmati minuman dan live music hingga larut malam.',
                'address' => 'Jl. Mulawarman Raya No.15, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50263',
                'district' => 'Banyumanik',
                'phone' => '081393371855',
                'instagram' => '@djagongan.id',
                'opening_hours' => '12:00 - 02:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Mixue Singosari',
                'category' => 'drink-area',
                'description' => 'Gerai es krim dan minuman manis populer, jadi favorit anak muda Semarang.',
                'address' => 'Jl. Singosari Raya No.79A, Pleburan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50241',
                'district' => 'Semarang Selatan',
                'phone' => '081903450888',
                'instagram' => '@mixue.singosarismg',
                'opening_hours' => '08:30 - 22:30',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Wedrink Mugas',
                'category' => 'drink-area',
                'description' => 'Tempat minuman kekinian dengan menu boba dan teh segar, cocok untuk nongkrong santai.',
                'address' => 'Jl. Tri Lomba Juang No.16, Mugassari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50249',
                'district' => 'Semarang Selatan',
                'phone' => '08163636390',
                'instagram' => '@wedrink_mugassemarang',
                'opening_hours' => '09:00 - 21:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'HW Tiger Club Semarang',
                'category' => 'drink-area',
                'description' => 'Club malam dengan suasana meriah, jadi destinasi hiburan anak muda Semarang Utara.',
                'address' => 'Jl. Cendrawasih No.24, Tj. Mas, Kec. Semarang Utara, Kota Semarang, Jawa Tengah 50174',
                'district' => 'Semarang Utara',
                'phone' => '02150886170',
                'instagram' => '@byholywings',
                'opening_hours' => '20:00 - 04:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'HW Helen\'s Night Market',
                'category' => 'drink-area',
                'description' => 'Night market dengan konsep bar, menghadirkan hiburan malam yang ramai di Candisari.',
                'address' => 'Jl. Diponegoro No.22A, Tegalsari, Kec. Candisari, Kota Semarang, Jawa Tengah 50251',
                'district' => 'Candisari',
                'phone' => null,
                'instagram' => '@byholywings',
                'opening_hours' => '20:00 - 04:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],

            // CATERING
            [
                'name' => 'Catering Berkah',
                'category' => 'catering',
                'description' => 'Layanan catering dengan menu rumahan, cocok untuk acara keluarga atau kantor.',
                'address' => 'Jl. Lempongsari Raya No.360, Lempongsari, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50231',
                'district' => 'Gajahmungkur',
                'phone' => '0248314423',
                'instagram' => null,
                'opening_hours' => '07:00 - 17:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Melati Catering & Snack Semarang',
                'category' => 'catering',
                'description' => 'Catering dengan spesialisasi snack box dan menu tradisional, populer untuk acara resmi.',
                'address' => 'Jl. Indrapura No.10A, Candi Baru, Lempongsari, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50231',
                'district' => 'Gajahmungkur',
                'phone' => '081328601404',
                'instagram' => '@melaticateringsnacks.official',
                'opening_hours' => '08:00 - 17:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Yunie Catering',
                'category' => 'catering',
                'description' => 'Catering dengan variasi menu Nusantara, menghadirkan rasa autentik untuk berbagai acara',
                'address' => 'Jl. Kelud Utara IV No.8, Petompon, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50237',
                'district' => 'Gajahmungkur',
                'phone' => '02476920979',
                'instagram' => '@yuniecatering',
                'opening_hours' => '08:00 - 17:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'Anggrek Catering Semarang',
                'category' => 'catering',
                'description' => 'Catering dengan menu praktis dan harga terjangkau, jadi pilihan untuk acara kecil.',
                'address' => 'Jl. Anggrek XI No.5, Pekunden, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50231',
                'district' => 'Semarang Tengah',
                'phone' => '0248413361',
                'instagram' => '@anggrekcatering',
                'opening_hours' => '08:30 - 16:00',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
            [
                'name' => 'La Catering Semarang New',
                'category' => 'catering',
                'description' => 'Catering modern dengan menu variatif, melayani acara besar maupun kecil di Semarang.',
                'address' => 'Jalan Sriwijaya Genuk karanglo, RT2/RW 2 Jl. Tegalsari Raya No.17, Tegalsari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50242',
                'district' => 'Semarang Selatan',
                'phone' => null,
                'instagram' => '@lacatering.semarang',
                'opening_hours' => '09:00 - 19:00 (Minggu Libur)',
                'rating' => 0.0,
                'reviews_count' => 0,
            ],
        ];

        foreach ($places as $place) {
            Place::create(array_merge($place, [
                'user_id' => $user->id,
            ]));
        }
    }
}
            